name: CI

on: [push, pull_request]

env:
  DATABASE_URL: "https://fakedb.com"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # Change the version as needed

      - name: Install dependencies
        run: npm install

      - name: Run TypeScript type checking
        run: npm run type-check

      - name: Run linting
        run: npm run lint
